name: 'Check Issues Due Date'

on:
  schedule:
    - cron: '16 12 * * *'

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Check duedate and write a comment
        uses: petrandr/duedate_reminders@latest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          project_number: 4
          notify_for: "expiring_issues"
          duedate_field_name: "Planned End"
          notification_type: "comment"
